<?php

namespace MMH\SiteBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

  public function getArticleWithImage()
  {
    return $this->createQueryBuilder('a')
    ->innerJoin('a.imagearticle', 'img')
    ->addSelect('img')
    ->getQuery()
    ->getResult();
  }

  public function getArticleWithAuthor($slug)
  {
    $qb =  $this->createQueryBuilder('a');
    $qb
      ->where ("a.slug = :slug")
      ->setParameter("slug",$slug)
      ;
      return $qb
    ->innerJoin('a.imagearticle', 'img')
    ->addSelect('img')
    ->innerJoin('a.user', 'use')
    ->addSelect('use')

    ->getQuery()
    ->getResult();
  }

}
