<?php

namespace MMH\SiteBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

  public function getArticleWithImage()
  {
    return $this->createQueryBuilder('a')
    ->innerJoin('a.imagearticle', 'img')
    ->addSelect('img')
    ->getQuery()
    ->getResult();
  }

}
