<?php

namespace MMH\SiteBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

  public function getProjectWithPayment()
  {
    return $this->createQueryBuilder('p')
    ->innerJoin('p.payment', 'pay')
    ->addSelect('pay')
    ->getQuery()
    ->getResult();
  }

}
