imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.project_images: bundles/mmhsite/img/projets
    app.path.article_images: /bundles/mmhsite/img/content
    app.path.user_images: /mymoneyhelp/web/bundles/mmhsite/img/user_images


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Stof\DoctrineExtensionsBundle configuration

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# File and images uploading bundle
vich_uploader:
    db_driver: orm
    mappings:
        project_images:
            uri_prefix:         %app.path.project_images%
            upload_destination: %kernel.root_dir%/../src/MMH/SiteBundle/Ressources/public/img/projets
        article_images:
            uri_prefix:         %app.path.article_images%
            upload_destination: %kernel.root_dir%/../src/MMH/SiteBundle/Ressources/public/img/content
        user_images:
            uri_prefix:         %app.path.user_images%
            upload_destination: %kernel.root_dir%/../src/MMH/SiteBundle/Ressources/public/img/user_images

# liip_imagine
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../web/bundles/mmhsite/img/projets"
                cache_prefix: "media/cache"

    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_carousel:

            # adjust the image quality to 75%
            quality: 80

            # list of transformations to apply (the "filters")
            filters:
                upscale: { min: [700, 400] }
                thumbnail: { size: [700, 400], mode: outbound }

                background: { size: [700, 400], position: center, color: '#ECF0F4' }


        # the name of the "filter set"
        my_cards:

            # adjust the image quality to 75%
            quality: 60

            # list of transformations to apply (the "filters")
            filters:
                upscale: { min: [300, 150] }
                thumbnail: { size: [300, 150], mode: outbound }

                background: { size: [300, 150], position: center, color: '#fff' }

        my_text_image:

            # adjust the image quality to 75%
            quality: 70

            # list of transformations to apply (the "filters")
            filters:
                upscale: { min: [350, 200] }
                thumbnail: { size: [350, 200], mode: outbound }

                background: { size: [350, 200], position: center, color: '#ECF0F4' }



# app/config/config.yml
easy_admin:
   site_name: 'MyMoneyHelp'
   entities:
       Amount:
         class: MMH\SiteBundle\Entity\Amount
       Article:
         class: MMH\SiteBundle\Entity\Article
         list:
             fields:
                 - title
                #  - { property: 'path', type: 'image', base_path: %app.path.article_images% }
                 - dateCreation
       imageArticle:
           class: MMH\SiteBundle\Entity\imageArticle
           list:
                 fields:
                     - id
                     - { property: 'path', type: 'image', base_path: %app.path.article_images%, label: 'Image' }
                     - article
       Payment:
         class: MMH\SiteBundle\Entity\Payment
       User:
         class: MMH\SiteBundle\Entity\User
       imageProject:
         class: MMH\SiteBundle\Entity\imageProject
         label: 'Images'
         list:
               fields:
                   - id
                   - { property: 'path', type: 'image', base_path: %app.path.project_images%, label: 'Image' }
                   - project
                   - headImage
                   - bodyImage
         form:
             fields:
                 - project
                 - headImage
                 - bodyImage
                 - { property: 'imageFile', type: 'vich_image' }

       Project:
         class: MMH\SiteBundle\Entity\Project
         label: 'Projets'
         list:
             fields:
                 - { property: 'title', label: 'Titre du projet'}
                 - { property: 'adminImage', type: 'image', base_path: %app.path.project_images%, label: 'Image' }
                 - { property: 'total', label: 'Total'}
                 - { property: 'finalObjective', label: 'Objectif final'}
                 - { property: 'status', type: 'boolean', label: 'En cours'}
                 - { property: 'endDate', label: 'fin du projet', format: 'd/m/Y'}
                 - { property: 'category', label: 'Categorie'}
         form:
             fields:
                 - 'title'
                 - { property: 'headline', label: "Phrase d'accroche (65 caractères max)"}
                 - { property: 'text', label: 'texte', type: 'ckeditor' }
                 - { property: 'finalObjective', label: "Montant à atteindre"}
                 - { property: 'endDate', label: 'fin du projet', format: 'd/m/Y'}
                 - amount
                 - { property: 'visibility', label: 'rendre ce projet visible sur le site' }
                 - { property: 'category', label: 'Categorie'}
                 - { property: 'user', label: 'Porteur de projet', type_options: { required: false }}
                 - facebook
                 - twitter
                 - linkedin
                 - pinterest
         Comment:
             class: MMH\SiteBundle\Entity\Comment
   design:
       brand_color: '#2da555'
