# Easy Admin
easy_admin_bundle:
  resource: "@EasyAdminBundle/Controller/"
  type:     annotation
  prefix:   /admin
  
mmh_admin:
    resource: "@MMHAdminBundle/Resources/config/routing.yml"
    prefix:   /

mmh_static:
    resource: "@MMHStaticBundle/Resources/config/routing.yml"
    prefix:   /

mmh_site:
    resource: "@MMHSiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Image resizer & filter
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
